services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./hass_config:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    restart: unless-stopped

  rf-bridge:
    container_name: rf-bridge
    build: .
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - ./remote_codes.json:/app/remote_codes.json
    ports:
      - "5000:5000"
    restart: always
